version: '3'
services:
  mango1:
    image: server
    environment:
      - APP=mango
      - ENDPOINT=localhost:8081
    ports:
      - "8081:5000"

  mango2:
    image: server
    environment:
      - APP=mango
      - ENDPOINT=localhost:8082
    ports:
      - "8082:5000"

  mango3:
    image: server
    environment:
      - APP=mango
      - ENDPOINT=localhost:9081
    ports:
      - "9081:5000"

  apple1:
    image: server
    environment:
      - APP=apple
      - ENDPOINT=localhost:9082
    ports:
      - "9082:5000"
